### ISSUE TITLE
Diagram of Typical Handler Workflow

### ISSUE THREAD

**Issue by sbellware** [eventide-project/docs#25]
In http://docs.eventide-project.org/user-guide/handlers.html#typical-handler-workflow, include a diagram like the one that @substantial-kst did.

Consider building in Plant UML.

**Comment by brennovich** [comment]
Perhaps [mermaid](https://github.com/mermaid-js/mermaid) could also be an option.

**Comment by sbellware** [comment]
@brennovich We're already working with PlantUML, so it's likely we'll keep on with it.

**Comment by sbellware** [comment]
Done
